### ISSUE TITLE
Some questions about applying for GSoC

### ISSUE THREAD

**Issue by sususama** [OpenVINO-dev-contest/meter-reader-openvino#1]
你好，请问您的项目现在有人多少人申请，有什么pretest吗？

**Comment by OpenVINO-dev-contest** [comment]
Hi @sususama 请用英文在这个仓库里提交你的问题，谢谢

https://github.com/openvinotoolkit/openvino_notebooks

**Comment by sususama** [comment]
能直接写邮箱之类的吗，我现在已经完成了社区的pretest，可以的话麻烦您提供一下您的邮箱，谢谢

**Comment by OpenVINO-dev-contest** [comment]
可以的，但麻烦你从notebook仓库发起请求，这样我们其他同事也看到，这个仓库目前不接受代码提交。
